version: "3.7"

services:
  karate-mysql:
    image: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "karate"
    ports: ["3307:3306"]
    volumes:
      - mysql_sita_data:/var/lib/mysql
    restart: always
    networks:
      - sita-wtropen

  karate-hw:
    image: sita/karate-hw:0.0.1-SNAPSHOT
    hostname: karate-hw
    restart: always
    ports: ["8088:8080"]
    networks:
      - sita-wtropen

  karate-ci:
    image: sita/karate-ci:0.0.1-SNAPSHOT
    hostname: karate-ci
    restart: always
    ports: []
    environment:
      - KARATE_ENVIRONMENT=docker
    volumes:
      - karate_nginx:/external/nginx/home
      - ../:/tmp/app/
      - maven_repo:/root/.m2/repository/
    networks:
      - sita-wtropen

  karate-nginx:
    image: nginx
    hostname: nginx
    restart: always
    ports: ["80:80"]
    volumes:
      - karate_nginx:/usr/share/nginx/html
    networks:
      - sita-wtropen

networks:
  sita-wtropen:
    external: true

volumes:
  maven_repo:
  karate_nginx:
  mysql_sita_data: