server:
  port: 8080
  servlet:
    context-path: /karate/hw
spring:
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
  mvc:
    date-format: dd/MM/yyyy HH:mm:ss
  gson:
    date-format: dd/MM/yyyy HH:mm:ss
